config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development? #sidekiq上のジョブ状況を見れるように設定
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development? #デベロップ環境で指定のURLにアクセスするとメールが見れるようになる設定

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index' # DAY8でhome#index→articles#indexに変更。呼び出すファイル名も変更必要
  # rootは”/”を意味する。特に指定がなければhomecontrollerのindexメソッドを実行。
  # また、html.erbでroot_pathメソッドを実行すると"/"ページへのURLが生成される

  # get '/' => 'home#index'
  # ↑ブラウザからサーバーへゲットリクエストが来た時にhomecontrollerのindexメソッドを実行。rootがあるのでコメントアウト
  #get '/about' => 'home#about' # 同上でaboutメソッドを実行

  resources :articles

  resources :accounts, only: [:show] do  #各ユーザーのプロフィールページに遷移できるように設定。userのURLはdeviseが使用しているので便宜的にaccountsとする。
    resources :follows, only: [:create] #フォロー機能を実装するために設定。
    resources :unfollows, only: [:create] #フォロー外す用。fllouwsにデストロイを追加する方法を採用しない理由として、railsのシンプルに設計したい思想を意識。
  end

  scope module: :apps do #controllerを「apps/〇〇〜」となるように変更。URLにappsを加える必要性がない。そういう時は利用者の混乱を避けるためにモジュールを使うという思想
    resources :favorites, only: [:index]
    resource :timeline, only: [:show]#タイムラインは一人一つなので単数

    resource :profile, only: [:show, :edit, :update]#プロフィールは一人一つなので単数で作成。URLもindexが作成されない。
  end

  namespace :api, defaults: {format: :json} do #apiに関するものだとわかるようにURLとコントローラーディレクトリを変更できる。formatはjsonを指定するとjsで動くようになる。
    scope '/articles/:article_id' do #URLだけを変更できる
      resources :comments, only: [:index, :create]
      resource :like, only: [:show, :create, :destroy]#destroyのしやすさ重視で単数。いいねは中間テーブルに新たなデータを作る作業なのでcreate。
    end
  end
end


 #入れ子にすることでarticles/comenntsのようなURLを作れる。
  # resourcesはURLを作成する機能。onlyを書くと、様々な機能のURLが作成されるがその中で指定したものだけを使用する意味になる
  # それぞれarticles_controllerの同名メソッドが実行される
  # newは新しい投稿を作成するためのフォームとしてrailsのCRUDに含まれている
  # updateを実行すると「localhost:3000/rails/info/routes」ページのarticle_pathにPUTとPATCHリクエストが追加される。
  # PUTとPATCHのURLは共にGETリクエストと同じだが、URLは同じでもリクエスト内容が異なるのでサーバー側での挙動も異なる。
  # GETは取得、PUTは更新（または作成）、PATCHは部分更新、DELETEは削除
  # destroyの追加でDELETEリクエストが追加される。

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#
class Article < ApplicationRecord
  validates :title, length: { minimum: 2, maximum: 100 } #文字の長さを検証。今回は二文字以上でないと登録できない
  validates :title, presence: true # validatesで指定したカラムについて検証できる。presence:trueで、titleが空欄の時は保存できないようにする
  validates :title, format: { with: /\A(?!\@)/ } #「titleの先頭は@以外」でないと登録できない処理。
                                                #\Aは先頭を表し、\@を(?!)の前に置くことで「＠以外」を指定。(?!)が無ければ先頭が＠でないと登録できない。

  validates :content, presence: true


  # validates :content, length: { minimum: 10}
  # validates :content, uniqueness: true #同じ内容があるか検証
  # # validatesの種類。length:長さを検証,format:正規表現か検証,numericality:数字の検証,presence:入力の有無を検証,uniqueness:唯一性を検証
  # validate :validat_title_and_content_length #独自に検証機能をつける場合は「validate」で実装する。複数形でないことに注意。検証内容は別に要定義
  #↑Action text実装に併せてまとめてコメントアウト。エラーになるらしい


  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy #記事から見たら中間テーブルのいいねは複数対象なのでこの書き方で紐付け
  belongs_to :user #記事はユーザーに紐付けられている、というような意味。記事から見たユーザーは一人なので単数系で書く。
  has_one_attached :eyecatch #記事に画像UPできるメソッドを定義
  has_rich_text :content #contentに対してAction textを使えるようにする設定



  # private
  # def validat_title_and_content_length
  #   char_count = self.title.length + self.content.length #chraは文字。タイトルとコンテントの文字数を検証。
  #   errors.add(:content, '100文字いじょうで！') unless char_count > 100 #文字数が100字以下だったら、エラー文を追加する処理。
  #                                                                   #独自の定義なのでエラー文も用意しないといけない
  # end
  #↑Action text実装に併せてコメントアウト。エラーになるらしい

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController # APから継承。DAY８の処理でhomecontrolle→articlescontrollerに変更（名称は基本的に複数形）。
  before_action :set_article, only: [:show]
  # 繰り返し使用するコードを自動で各メソッドの一番最初に定義するアクション。onlyで特定のメソッドだけに適用できる。
  # 繰り返したいコードはset_articleメソッド内に定義しておく。
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  #ログインしていないとすべてのアクションが行えなくなる処理。onlyでどの行為を制限するか指定できる。

  def index # railsで定義されているメソッド。様々な処理を内包する。
    @articles = Article.all # インスタンス変数。indexメソッドを実行して表示されるerb内で使用可能。.firstなら1個目、.allなら全てのデータを取得
    # Articleモデルのデータベースからデータを取得するメソッド
  end

  # def about DAY８の処理に不要なのでコメントアウト。ファイルも削除
  # render "home/about" #homeフォルダのaboutファイルを表示する。indexメソッドには初期搭載されているため省略される
  # DAY８追加コメント（indexのrenderではself/indexのような形になってる気がする。だからindexで呼び出すディレクトリ名も変える必要がある）
  # end

  def show
    #↓jsを使用して表示するので不要になりコメントアウト
    # @comments = @article.comments #beforeアクションで定義されている@articleを使い、インスタンスに取得した記事とコメントを紐付けて代入

  end

  def new
    @article = current_user.articles.build #現在ログインしているユーザーと記事を紐付けて空のデータを作る際の書き方
    # @article = Article.new # Articleモデルにnewを行い、中身が空のデータを新しく作る。既存の機能でrenderを実行しなくともnew.html.erbを探し表示させる。
  end

  def create
    @article = current_user.articles.build(article_params)#現在ログインしているユーザーと記事を紐付けて空のデータを作る際の書き方
    # @article = Article.new(article_params) # データが空の箱を作る。引数で箱にはtitleとcontentを入れるスペースがある。
    if @article.save # 作成したデータを保存するメソッド。保存できたかを確認するためif文で保存できたらその投稿のページに遷移するようにする
      redirect_to article_path(@article), notice: '保存できたよ' # noticeと文字列はflashメッセージのキーとバリュー
    # ↑指定したpathのページに遷移するメソッド。article_pathと引数で記事の該当ページへの遷移を指定。noticeで遷移時の文言を指定（HTMLにも要記載）
    else
      flash.now[:error] = '保存に失敗しました' # 保存できなかった場合のflashメッセージをキーとバリューで指定。redirect時とは書き方が異なるが処理は同じ
      render :new # 保存できなかった場合にnewを実行。
      # これで表示されたnew.html.erb内の@articlesは本メソッド内で定義された変数であり、表示前の入力データが一時保存されて表示される。
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])#現在ログインしているユーザーの記事の中から指定したIDの記事を探す。
    #ログイン中のユーザーに限定しないと、他人の記事を探して編集できてしまうので注意
    # @article = Article.find(params[:id]) #DBからparamsのIDに該当する情報を抜き出す。ID１なら１記事目の編集画面が出るようにedit.html.erbを作成
  end

  def update
    @article = current_user.articles.find(params[:id])#現在ログインしているユーザーの記事の中から指定したIDの記事を探す。
    #ログイン中のユーザーに限定しないと、他人の記事を探して編集できてしまうので注意
    # @article = Article.find(params[:id]) #リクエスト時のURLにidが記載されているため、サーバー側で該当IDを受け取ることができる。
    # 受け取ったそのIDがparamsに反映される。反映されたidに該当するデータを抜き出す
    if @article.update(article_params) # 値を更新するメソッド。article_paramでどの値を更新するか決める。今回はtitleとcontentが指定されている
      redirect_to article_path(@article), notice: '更新できました' # createメソッドと同内容で文字列だけ変更
    else
      flash.now[:error] = '更新に失敗しました'
      render :new
    end
  end

  def destroy # 本メソッド内のarticleはメソッド内だけで処理が完結しており、erbに記述する必要がないのでインスタンス変数にはしない。
    # インスタンス変数にしてしまうとrailsに慣れた人に「もしかしてerbに記載しているのかな？」と誤解させてしまう可能性が高いため。
    article = current_user.articles.find(params[:id]) # 現在ログインしているユーザーの削除したいデータを取得
    article.destroy! # データを削除するメソッド。！は無くても実行可。！あると処理が完了しなかった場合に例外が発生しエラーになる
    redirect_to root_path, notice: '削除に成功しました' # 削除したら記事一覧に戻り、通知を出す
  end

  private # paramsのメソッドを作る際にはつけることになっている

  def article_params # ブラウザ側からサーバーに送られるデータ（パラメーター）のうち、何を保存するか選択するメソッドを作成する。
    # _paramsの前は更新するモデル名に合わせるルール。今回はArticleモデルのデータを更新する
    params.require(:article).permit(:title, :content, :eyecatch)
    # 送られたデータはハッシュの形になっているので、その中のキーがarticleのデータだけ読み込み、さらにデータのtitleとcontentだけ保存を許可する処理
    # ブラウザ側から不正なデータを送られて保存してしまわないようにセキュリティ上かなり重要
  end

  def set_article # before_actionで指定する繰り返し使いたいコードを内包したメソッド
    @article = Article.find(params[:id])#ArticleモデルDBから指定されたIDのデータを取得する。paramsはパラメータ的な意味。:idと記載するルール
  end
end

app/views/articles/_article.html.haml
= link_to article_path(article) do
  .card
    .card_image
      = image_tag 'eyecatch1.png'
    .card_content
      .card_title
        = article.title
      .card_heart
        = image_tag 'heart.svg'
        %span 23
      .card_detail
        = image_tag 'default-avatar.png'
        %div
          %p= article.author_name
          %p= article.display_created_at

app/views/articles/_form.html.haml
.container
  %ul
    - article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: article, local: true) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.rich_text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/articles/_tabs.html.haml
.tabs
  .tabs_item.active
    新着記事一覧
  .tabs_item
    タイムライン

app/views/articles/edit.html.haml
= render 'form', article: @article
\&lt;%#

app/views/articles/index.html.haml
= render 'commons/articles', articles: @articles

app/views/articles/new.html.haml
= render 'form', article: @article

app/views/articles/show.html.haml
.article#article-show{data: {article_id: @article.id}}
  -#article-showというidを追加し、さらにarticle_idのdataとして現在の記事のIDを渡すように設定。このdataをjsで取得すれば現在どの記事を開いているかjs側で認識できる。
  - if @article.eyecatch.attached?
    -#UPされた画像があればそれを表示。なければデフォルトに。
    .article_image
      = image_tag @article.eyecatch
  %h1.article_title= @article.title
  .article_detail
    = link_to account_path(@article.user) do
      = image_tag @article.user.avatar_image
    %div
      %p= @article.author_name
      %p= @article.display_created_at
    - if user_signed_in? && current_user.has_written?(@article)
      .article_detail_actions
        .dropdown
          = image_tag 'actions.svg', class: 'dropbtn'
          .dropdown-content.mini
            = link_to '編集する', edit_article_path(@article)
            = link_to '削除する', article_path(@article), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
  .article_content
    = @article.content
  - if user_signed_in?
    .article_heart.hidden.active-heart
      = image_tag 'heart-active.svg'
    .article_heart.hidden.inactive-heart
      = image_tag 'heart.svg'
-#いいねの表示をJSで行うように変更。Rubyのコードがあると動かないのでif文を削除し、hiddenとactiveクラスを追加。常に隠しておき、いいねがtureだったらhiddenクラスを削除して表示されるようにapplication.jsに記載。
-#さらにいいねした時にリンクからリダイレクトしていた処理をjsによる処理に変更。

.article
  %h2= I18n.t('articles.comment_list')
  .comments-container
  -# - @comments.each do |comment|
  -#   .article_comment
  -#     %p= comment.content　jsで表示するため不要になりコメントアウト


.container
  .btn-secondary.show-comment-form
    コメントを追加
    -#↑をクリックしたら↓が表示されるようにjsでイベント処理を書く。jsで書くためのクラスを追加する。
  .comment-text-area.hidden
    = text_area_tag :comment_content, '', class: 'sm'
    -#htmlのテキストエリアを生成するhelperタグ。name（キー）は適当。初期値は空。
    .btn-secondary.add-comment-button
      コメントを追加

= javascript_pack_tag 'article'
-# view表示に関するjsファイルを読み込む。jsサーバー要再起動。