config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development? #sidekiq上のジョブ状況を見れるように設定
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development? #デベロップ環境で指定のURLにアクセスするとメールが見れるようになる設定

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index' # DAY8でhome#index→articles#indexに変更。呼び出すファイル名も変更必要
  # rootは”/”を意味する。特に指定がなければhomecontrollerのindexメソッドを実行。
  # また、html.erbでroot_pathメソッドを実行すると"/"ページへのURLが生成される

  # get '/' => 'home#index'
  # ↑ブラウザからサーバーへゲットリクエストが来た時にhomecontrollerのindexメソッドを実行。rootがあるのでコメントアウト
  #get '/about' => 'home#about' # 同上でaboutメソッドを実行

  resources :articles

  resources :accounts, only: [:show] do  #各ユーザーのプロフィールページに遷移できるように設定。userのURLはdeviseが使用しているので便宜的にaccountsとする。
    resources :follows, only: [:create] #フォロー機能を実装するために設定。
    resources :unfollows, only: [:create] #フォロー外す用。fllouwsにデストロイを追加する方法を採用しない理由として、railsのシンプルに設計したい思想を意識。
  end

  scope module: :apps do #controllerを「apps/〇〇〜」となるように変更。URLにappsを加える必要性がない。そういう時は利用者の混乱を避けるためにモジュールを使うという思想
    resources :favorites, only: [:index]
    resource :timeline, only: [:show]#タイムラインは一人一つなので単数

    resource :profile, only: [:show, :edit, :update]#プロフィールは一人一つなので単数で作成。URLもindexが作成されない。
  end

  namespace :api, defaults: {format: :json} do #apiに関するものだとわかるようにURLとコントローラーディレクトリを変更できる。formatはjsonを指定するとjsで動くようになる。
    scope '/articles/:article_id' do #URLだけを変更できる
      resources :comments, only: [:index, :create]
      resource :like, only: [:show, :create, :destroy]#destroyのしやすさ重視で単数。いいねは中間テーブルに新たなデータを作る作業なのでcreate。
    end
  end
end


 #入れ子にすることでarticles/comenntsのようなURLを作れる。
  # resourcesはURLを作成する機能。onlyを書くと、様々な機能のURLが作成されるがその中で指定したものだけを使用する意味になる
  # それぞれarticles_controllerの同名メソッドが実行される
  # newは新しい投稿を作成するためのフォームとしてrailsのCRUDに含まれている
  # updateを実行すると「localhost:3000/rails/info/routes」ページのarticle_pathにPUTとPATCHリクエストが追加される。
  # PUTとPATCHのURLは共にGETリクエストと同じだが、URLは同じでもリクエスト内容が異なるのでサーバー側での挙動も異なる。
  # GETは取得、PUTは更新（または作成）、PATCHは部分更新、DELETEは削除
  # destroyの追加でDELETEリクエストが追加される。

app/views/commons/_article.html.haml
= link_to article_path(article) do
  .card
    - if article.eyecatch.attached?
      .card_image
        = image_tag article.eyecatch
    .card_content
      .card_title
        = article.title
      .card_heart
        = image_tag 'heart.svg'
        %span= article.like_count
      .card_detail
        = image_tag article.user.avatar_image
        %div
          %p= article.author_name
          %p= article.display_created_at

app/views/commons/_articles.html.haml
.container
  = render 'commons/tabs'
  - articles.each do |article|
    = render 'commons/article', article: article
  = link_to new_article_path do
    .float_btn
      %i.fa.fa-plus

app/views/commons/_profile.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = image_tag user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          #{user.display_name}（#{user.age || '？歳'}・#{I18n.t("enum.genders.#{user.gender || 'unknown'}")}）
        -#ログイン中ユーザーについて「名前（生年月日・性別）」の形式で表示。rubyのコードを埋め込む書き方
        .profilePage_user_actionButton
          - if user == current_user
            = link_to 'Edit', edit_profile_path
          - else
            - if current_user&.has_followed?(user)
              = link_to 'Unfollow', account_unfollows_path(user), data: {method: 'post'}
            - else
              = link_to 'Follow', account_follows_path(user), data: {method: 'post'}
      .profilePage_user_introduction
        = user.profile&.introduction

  - user.articles.each do |article|
    = render 'commons/article', article: article

    -#自分と他人のプロフィールページを共通化
    -#年齢が未入力なら「？歳」と表示されるように設定。性別も同様の設定（enum.ja.yamlファイルにも「unknown: '性別未入力'」の記載追加が必要）。
    -#ログイン中のユーザー自身のページだったら編集ボタンが、他者のページだったらフォローボタンが表示されるように設定。
    -#フォローしてたらボタン表示が変わるように設定。ぼっち演算子にしないとログインしていない時にエラーになる

app/views/commons/_tabs.html.haml
.tabs
  .tabs_item{class: "#{add_active_class(root_path)}"}
    = link_to '新着記事一覧', root_path
  .tabs_item{class: "#{add_active_class(timeline_path)}"}
    = link_to 'タイムライン', timeline_path

  -# 現在のページが指定したパスのページだったらクラスを適用するメソッドをhelperに記述してある。viewにRubyのコードを書くのは望ましくないため、viewを拡張するメソッドはhelperに集約させる。
  -# helperよりもDecoratorの方が直感的な記述になる。